# Generated by Django 4.2.4 on 2023-08-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_alter_city_options_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
