# Generated by Django 4.2.4 on 2023-08-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
    ]
