# Generated by Django 4.2.4 on 2023-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_city_culinary_delights_city_current_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='current_population',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='permanent_address_population',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
